import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import FileSideBar from "@/components/FileSideBar/FileSideBar";
import MainSideBar from "@/components/MainSideBar";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("bg-[#040D12] text-white", inter.className)}>
        <div className="flex items-center justify-center border-b">
          <h1 className="text-3xl font-bold mt-3 mb-3">Header</h1>
        </div>
        <div className=" flex flex-row h-20">
          <div className="w-20 bg-black border-r mt-5">
            <FileSideBar />
          </div>
          <div className="w-60 bg-black/90 border-r mt-5">
            <MainSideBar />
          </div>
          <div className=" mt-5">{children}</div>
        </div>
      </body>
    </html>
  );
}
